### ISSUE TITLE
adding explore button to empty lists for better ux

### ISSUE THREAD

**Issue by omerozceylan** [fdemir/watchandchill-community#1]
**Is your feature request related to a problem? Please describe.**

nope

**Describe the solution you'd like**

add a explore button to middle of site.

**Describe alternatives you've considered**

there is no alternatives

**Additional context**

https://prnt.sc/Iqz_GiB0M66Z

**Comment by fdemir** [comment]
<img width="1198" alt="image" src="https://github.com/fdemir/watchandchill-community/assets/48316033/8f26f928-3374-499f-939e-1bc4528b10c7">
Released. V: 1.1.4

**Comment by omerozceylan** [comment]
looks good
